on:
  workflow_dispatch:
  
name: App workflow

env:
  VERSION: "2.0"

jobs:
  build_app:
    name: Build app
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building app"
  unit_tests:
    name: Unit tests
    needs: build_app
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running unit tests"
  deploy_app:
    name: Deploy app
    needs: unit_tests
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying app"
