apiVersion: v1
kind: cypress
sauce:
  region: us-west-1
  concurrency: 10 
  metadata:
    tags:
      - e2e
      - release team
      - other tag
    build: Automated tests run 1
docker:
  fileTransfer: copy 
cypress:
  version: 10.7.0 
  configFile: "cypress.config.js"

reporters:
  junit:
    enabled: true
    filename: saucectl-junit-report.xml

rootDir: ./
suites:
  - name: "Chrome" 
    browser: "chrome"
    platformName: "Windows 11" 
    screenResolution: "1920x1080" 
    shard: spec 
    config:
      specPattern: [ "cypress/e2e/**/*.*" ] 
  - name: "Firefox" 
    browser: "firefox"
    platformName: "Windows 11" 
    screenResolution: "1920x1080"  
    shard: spec 
    config:
      specPattern: [ "cypress/e2e/**/*.*" ]

artifacts:
  download:
    when: always
    match:
      - console.log
    directory: ./artifacts/
